### ISSUE TITLE
gold does linker scripts now

### ISSUE THREAD

**Issue by realtime-neil** [mattst88/build-id#3]
I think your information...

> Use a linker script to insert start/end symbols around the .note.gnu.build-id. Failed when reading the build-id of a shared object for unknown reasons. _Incompatible with gold, which does not use linker scripts._
-- https://github.com/mattst88/build-id/blob/master/README.md#other-proposed-and-failed-solutions , emphasis mine

...might be out of date:

> -T FILE, --script FILE
>   Read linker script
-- http://manpages.ubuntu.com/manpages/trusty/man1/ld.gold.1.html

**Comment by mattst88** [comment]
Interesting! I checked the binutils code and it looks like gold always supported linker scripts... I guess it doesn't have a default linker script, so maybe that's where my bad information originated from.

I saw the ld-build-id branch in your repo. Obviously `ld.gold --verbose` doesn't output a linker script you can use, so is there another way to make that solution work with gold?

**Comment by realtime-neil** [comment]
You're exactly correct: `ld.gold --verbose` can't produce a default linker script, but `CFLAGS+=-fuse-ld=gold` seems to convince `gcc` to use it. At the very least, it doesn't error out --- I can't prove (yet) that `gold` did the work.

**Comment by realtime-neil** [comment]
Nope, nevermind; on my `ld-build-id` branch, overriding `CFLAGS` to include `-fuse-ld=gold` is effectively a no-op since the linking step doesn't include that variable. If, however, I override `LDFLAGS=-fuse-ld=gold`, then it chokes with

```
gcc -fuse-ld=gold -Wl,--build-id=sha1 -Wl,--script=ld-build-id.ld ld-build-id.o -o ld-build-id -ldl
/usr/bin/ld.gold: error: ld-build-id.ld:51:22: syntax error, unexpected '('
/usr/bin/ld.gold: fatal error: unable to parse script file ld-build-id.ld
```

What's interesting is that this linker script syntax error occurs _after_ my twiddling around `.node.gnu.build-id`, so... _maybe_ `gold` would support it? I really need to teach myself more linker script.

But here's something neat:

```
$ PATH="/usr/lib/llvm-9/bin:${PATH}" CC=gcc LDFLAGS=-fuse-ld=lld make clean ld-build-id                  
rm -f build-id so-build-id dlopen-build-id ld-build-id ld-build-id.ld libbuild-id.so *.o *.result *.expected
gcc -fPIC   -c -o ld-build-id.o ld-build-id.c
ld --verbose | sed -r \
-e '1,/^={50}$/d' \
-e '/^={50}$/,$d' \
-e 's|([*][(].note.gnu.build-id[)])|__note_gnu_build_id_begin = .; \1; __note_gnu_build_id_end = .;|' \
>ld-build-id.ld
gcc -fuse-ld=lld -Wl,--build-id=sha1 -Wl,--script=ld-build-id.ld ld-build-id.o -o ld-build-id -ldl
```

Apparently, the `lld` shipping with `clang-9` likes the `ld` script format just fine, but the resulting program segfaults.
