### ISSUE TITLE
dlpi_name can be null sometimes.

### ISSUE THREAD

**Issue by Klayflash** [mattst88/build-id#5]
Hello!

Thanks for the library. I'm using it on Android with conjunction [xUnwind](https://github.com/hexhacking/xUnwind).

I've found that android x86 apiLevel=23 (emulator) sometimes call `build_id_find_nhdr_callback` function with nullptr of `info->dlpi_name`
If I change

```C
static int
build_id_find_nhdr_callback(struct dl_phdr_info *info, size_t size, void *data_)
{
(...)
    if (data->tag == BY_NAME && strcmp(info->dlpi_name, data->name) != 0)
        return 0;
```
to 
```C
static int
build_id_find_nhdr_callback(struct dl_phdr_info *info, size_t size, void *data_)
{
(...)
    if (data->tag == BY_NAME && (!info->dlpi_name || strcmp(info->dlpi_name, data->name) != 0))
        return 0;
```

then works fine: buildId is arrived successfully.

On apiLevel=30 is not reproduced.

**Comment by mattst88** [comment]
Interesting, thanks!

Would you like to make a pull request?

**Comment by Klayflash** [comment]
I'm not pretend to history of the commit records, so you can do it yourself.

Thanks for the offer.
